# Generated by Django 4.2.1 on 2023-06-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_remove_todo_product_end_remove_todo_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='jenis_barang',
            field=models.CharField(default='', max_length=180),
        ),
    ]
