# Generated by Django 4.2.1 on 2023-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_todo_jenis_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='harga_barang',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='todo',
            name='marketplace',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='todo',
            name='promo_value',
            field=models.CharField(default='', max_length=180),
        ),
    ]
