# Generated by Django 4.2.1 on 2023-06-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_todo_harga_barang_todo_marketplace_todo_promo_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='harga_barang',
            field=models.CharField(blank=True, default='', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='jenis_barang',
            field=models.CharField(blank=True, default='', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='marketplace',
            field=models.CharField(blank=True, default='', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='promo_value',
            field=models.CharField(blank=True, default='', max_length=180, null=True),
        ),
    ]
